### PR TITLE
Add translation to brazilian portuguese

### PR DESCRIPTION
**Pull request by Felipefpl**
1st i want to thank the ones who are developing this mod, thank you.

2nd - i'd like to ask to check if all strings are correctly displayed, the words/phrases are usually bigger in portuguese than in english, i believe this is the case with other languages too.

### CODE REVIEW

**Comment by anongit** [comment]
Hi, sorry for the late response.

>  i'd like to ask to check if all strings are correctly displayed, the words/phrases are usually bigger in portuguese than in english, i believe this is the case with other languages too.

I think it's fine, the phrases have about the same length as the ones in the `italian.tra` file.

However you changed the `english.tra` file instead of creating a new file. 
I can close this pull request and make the necessary changes myself, if you want, and if you don't, you will need to create a new file in the `dragonspear_ui++/tra/` folder, for example `brazilian.tra`, and also add the following lines in `dragonspear_ui++/dragonspear_ui++.tp2`:
```
LANGUAGE
       ~Brazilian Portuguese (by Felipefpl)~ ~dragonspear_ui++/tra/brazilian.tra~ ~dragonspear_ui++/tra/brazilian.tra~
```
This is for the language selection menu that appears during installation, with the changes above it look like this:
<p align=center>

</p>

**Comment by Felipefpl** [comment]
hi, i updated everything as you said, i hope it's fine now.

**Comment by anongit** [comment]
Almost, filenames don't match. In `dragonspear_ui++/dragonspear_ui++.tp2` it's `dragonspear_ui++/tra/brazilian.tra`, but you uploaded `dragonspear_ui++/tra/brazilian portuguese.tra`, you need to change one or another.

**Comment by Felipefpl** [comment]
Oops, fixed. :P

**Comment by anongit** [comment]
Okay, I fixed the last thing and squashed all commits.

**Pull request closed without merging**
